
SELECT 
    a.NUME,
    a.PRENUME, 
    a.FUNCTIE,
    td.COD_DECLARATIE,
    td.DENUMIRE
FROM ANGAJATI a
LEFT JOIN DECLARATII_FISCALE df ON df.ID_ANGAJAT = a.ID_ANGAJAT
LEFT JOIN TIPURI_DECLARATII td ON td.ID_TIP_DECLARATIE = df.ID_TIP_DECLARATIE
ORDER BY a.NUME, td.COD_DECLARATIE;