

SELECT SYSDATE + 2
FROM DUAL;

SELECT *
FROM EMPLOYEES
WHERE MOD(TRUNC(SYSDATE - HIRE_DATE), 7) = 0;


SELECT
    LAST_NAME, SALARY,
    RPAD('$', TRUNC(SALARY/1000), '$') as nivel_salariu
FROM EMPLOYEES;