SELECT * FROM USER_TABLES
WHERE TABLE_NAME LIKE '%RAUL';


SELECT L.COUNTRY_ID, COUNT(E.EMPLOYEE_ID) AS EMP_COUNT
FROM LOCATIONS L
JOIN DEPARTMENTS D ON L.LOCATION_ID = D.LOCATION_ID
LEFT JOIN employees E ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY COUNTRY_ID
ORDER BY EMP_COUNT DESC;
